UI_url = "https://www.chitai-gorod.ru/"
API_base_url = "https://web-agr.chitai-gorod.ru/web/api/v2/search"
Token = "Сюда впишите актуальный токен"
Invalid_token = ("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleH"
                 "AiOjE3NTkzMjUwOTUsImlhdCI6MTc1OTE1NzA5NSwiaX"
                 "NzIjoiL2FwaS92MS9hdXRoL2Fub255bW91cyIsInN1YiI"
                 "6IjEwZDBhM2U4ZTVhZTk0OTk1NzA4ZjExN2NkNjkxMGY1"
                 "YjNiZjQ3ZjJiYzk1ODFmZDU4NWFiOGQ3ZTc4ZmFjMDciL"
                 "CJ0eXBlIjoxMH0.fBlo5hEVJnOdIlc0KR75reNBvAn2-"
                 "80IGMO-N8NX4qs")
